language: node_js
sudo: false

node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

before_script:
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.3.8/nats-streaming-server-v0.3.8-linux-amd64.zip -O tmp.zip
  - unzip tmp.zip
  - mv nats-streaming-server-v0.3.8-linux-amd64 nats-streaming-server
  - mv nats-streaming-server/nats-streaming-server-v0.3.8 nats-streaming-server/nats-streaming-server


after_success:
  - npm run coveralls
