language: node_js
sudo: false

node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

before_script:
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.5.0/nats-streaming-server-v0.5.0-linux-amd64.zip -O tmp.zip
  - unzip tmp.zip
  - mv nats-streaming-server-v0.5.0-linux-amd64 nats-streaming-server
  - mkdir nats-streaming-server/logs


after_success:
  - npm run coveralls

after_failure:
  - cat nats-streaming-server/logs/*.log